/*
 * Minesweeper
 *
 * Backend API for a minesweeper game app
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	mineserver "github.com/leonardoneumann/minesweeperapi/api"
)

func main() {
	log.Printf("Minesweeper Api Server Started !")

	router := mineserver.NewRouter()

	//add static folder serve
	router.PathPrefix("/").Handler(http.FileServer(http.Dir("./static/swagger/")))

	log.Fatal(http.ListenAndServe(os.Getenv("PORT"), router))
}
