/*
 * Minesweeper
 *
 * Backend API for a minesweeper game app
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"
	"os"

	mineserver "github.com/leonardoneumann/minesweeperapi/api"
)

func main() {
	port := os.Getenv("PORT")
	log.Printf("Minesweeper Api Server Started ! - Listening on port : " + port)

	router := mineserver.NewRouter()

	//add static folder serve
	router.PathPrefix("/").Handler(http.FileServer(http.Dir("./static/swagger/")))

	log.Fatal(http.ListenAndServe(":"+port, router))
}
