/*
 * Minesweeper
 *
 * Backend API for a minesweeper game app
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type CellAction struct {
	Id int32 `json:"id"`

	// Cell State:    * `0` - Reveal    * `1` - Flag    * `2` - Question Mark
	Action int32 `json:"action"`
}
