/*
 * Minesweeper
 *
 * Backend API for a minesweeper game app
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type User struct {
	Id int32 `json:"id,omitempty"`

	Username string `json:"username"`

	Email string `json:"email"`

	Password string `json:"password"`
}
