/*
 * Minesweeper
 *
 * Backend API for a minesweeper game app
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

import (
	"time"
)

type AuthToken struct {
	Token string `json:"token,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`
}
